# Generated by Django 4.0.6 on 2022-08-02 06:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_customer_gender_customer_martialstatus_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='serial_number',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='card',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='date_issued',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='name',
        ),
        migrations.AddField(
            model_name='account',
            name='account_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='account',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='card',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='card',
            name='card_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='issue_date',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='issuer',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='security_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='customer',
            name='employment_status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='proile_picture',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.ImageField(default='default.jpg', upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='loan',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='guarantor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.thirdparty'),
        ),
        migrations.AddField(
            model_name='loan',
            name='interest_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_Term',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='loan',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='bill_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_file',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='bonus',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='gender',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='recipient',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='reward',
            name='reward_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='currency',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='location',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='name',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='phone_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='thirdparty',
            name='transaction_account',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='origin_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_charge',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transactionreciept',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.wallet'),
        ),
        migrations.AlterField(
            model_name='card',
            name='expiry_date',
            field=models.DateTimeField(default=' '),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='martialStatus',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='loan',
            name='payment_due_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='receipt_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date_of_reward',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.CharField(max_length=23, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wallet_customer', to='wallet.customer'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='dateCreated',
            field=models.DateTimeField(default=''),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='isActive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='pin',
            field=models.CharField(default='', max_length=15),
        ),
    ]
