# Generated by Django 4.0.6 on 2022-08-02 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_rename_serial_number_card_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Notification_recipient', to='wallet.customer'),
        ),
    ]
