# Generated by Django 4.0.6 on 2022-08-02 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_notification_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('f', 'fixed account'), ('c', 'current')], max_length=30, null=True),
        ),
    ]
