# Generated by Django 4.0.6 on 2022-08-02 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_remove_account_type_alter_account_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('f', 'fixed account'), ('c', 'current account')], max_length=30, null=True),
        ),
    ]
