# Generated by Django 4.0.6 on 2022-08-02 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0011_alter_loan_loan_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
