# Generated by Django 4.0.6 on 2022-08-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0013_alter_customer_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
