# Generated by Django 4.0.6 on 2022-08-19 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0015_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionreciept',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.receipt'),
        ),
    ]
