# Generated by Django 4.0.6 on 2022-08-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0017_alter_card_card_type_alter_card_issuer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transactionreciept',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
